unless (Ngage.EventDefinitionQueries.any) do
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User signed up"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User logged in"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User logged out"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User purchased credits"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User submitted email form"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User started demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User started standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 1 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 1 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 2 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 2 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 3 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 3 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 4 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 4 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 5 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 5 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 6 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 6 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 7 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 7 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 8 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 8 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 9 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 9 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 10 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen 10 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen >10 in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User generated gen >10 in standard session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User marked inactive for 5 days"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User marked inactive for 14 days"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User marked inactive for 30 days"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User experienced system crash in demo session"}))
    Ngage.EventDefinitionQueries.create(Ngage.EventDefinitions.changeset(%Ngage.EventDefinitions{}, %{description: "User experienced system crash in standard session"}))
end

unless (Ngage.CustomerQueries.any) do
    Ngage.CustomerQueries.create(Ngage.Customers.changeset(%Ngage.Customers{}, %{username: "pack3754@gmail.com"}))
    Ngage.CustomerQueries.create(Ngage.Customers.changeset(%Ngage.Customers{}, %{username: "nhpackard@protolife.com"}))
end

unless (Ngage.EventQueries.any) do
    Ngage.EventQueries.create(Ngage.Events.changeset(%Ngage.Events{}, %{customer_id: 1, event_definition_id: 1}))
    Ngage.EventQueries.create(Ngage.Events.changeset(%Ngage.Events{}, %{customer_id: 2, event_definition_id: 2}))
end
